data=[
    {"Name":"Shreya Ghosal","Country":"India","Occupation":"Singer","Follower":800},
    {"Name":"Niraj Chopra","Country":"India","Occupation":"Athlete","Follower":200},
    {"Name":"Twailor Swift","Country":"US","Occupation":"Singer","Follower":1000},
    {"Name":"MS Dhoni","Country":"India","Occupation":"Cricketer","Follower":900},
    {"Name":"Shah Rukh Khan","Country":"India","Occupation":"Actor","Follower":1500},
    {"Name":"Messi","Country":"Argentina","Occupation":"Football Player","Follower":1100},
    {"Name":"Cristano Ronaldo","Country":"Brazil","Occupation":"Football Player","Follower":1800},
    {"Name":"GLenn","Country":"Australia","Occupation":"Cricketer","Follower":650},
    {"Name":"Robert Doweny Jr.","Country":"UK","Occupation":"Actor","Follower":2000},
    {"Name":"Narendra Modi","Country":"India","Occupation":"Prime Minister","Follower":900},
    {"Name":"Mark JukerBark","Country":"America","Occupation":"CEO Of Meta","Follower":950},
    {"Name":"Sundar Puchai","Country":"India","Occupation":"CEO Of Google","Follower":752},
    {"Name":"Mukesh Ambani","Country":"India","Occupation":"Businessman","Follower":520},
    {"Name":"Ratan Tata","Country":"India","Occupation":"CEO of Tata","Follower":810},
    {"Name":"Justin Beibar","Country":"Canada","Occupation":"Singer","Follower":1800},
    {"Name":"Shlok Srivastava","Country":"India","Occupation":"Youtuber","Follower":1540},
    {"Name":"Elon Mask","Country":"India","Occupation":"CEO of Tesla Motors)","Follower":780},
    {"Name":"Joe Biden","Country":"America","Occupation":"President","Follower":457},
    {"Name":"Dolan Trumph","Country":"America","Occupation":"American Politition","Follower":890},
    {"Name":"Hima Das","Country":"India","Occupation":"Athlete","Follower":672},
    {"Name":"PV Shindu","Country":"India","Occupation":"Athlete","Follower":874},
    {"Name":"Lachhu Maharaj Ji","Country":"India","Occupation":"Dancer","Follower":250},
    {"Name":"Bill Gates","Country":"America","Occupation":"American Investor","Follower":560},
    {"Name":"Fimio Kisida","Country":"Japan","Occupation":"Japan president","Follower":715},
    {"Name":"Kim Kardashian","Country":"America","Occupation":"Public figure","Follower":120},
    {"Name":"Barack Obama","Country":"African American","Occupation":"President of the United States of America","Follower":788},
    {"Name":"Shakira","Country":"Coloumbia","Occupation":"Musician","Follower":945},
    {"Name":"Jeff Bezos","Country":"UK","Occupation":" founder and CEO of Amazon.com","Follower":566},
    {"Name":"Dwayne Johnson","Country":"US","Occupation":"Actor, Wrestler","Follower":689},
    {"Name":"Johnny Depp","Country":"America","Occupation":"Actor","Follower":745},
    {"Name":"Lady Gaga","Country":"America","Occupation":"Singer","Follower":370},
    {"Name":"Amitabh Bachchan","Country":"India","Occupation":"Actor","Follower":659},
    {"Name":"Gautam Adani","Country":"India","Occupation":"Founder and Chairman of Adani Group","Follower":1299},
    {"Name":"Narayana Murthy","Country":"India","Occupation":"entrepreneurs","Follower":779},
    {"Name":"Eishwar N Maanay","Country":"India","Occupation":"dynamic and visionary Dean of BNM Institute of Technology","Follower":898},
    {"Name":"Sachin Ramesh Tendulkar","Country":"India","Occupation":"Cricketer","Follower":856},
    {"Name":"Johnny Depp","Country":"US","Occupation":"Producer,Actor","Follower":864},
    {"Name":"Tom Cruise","Country":"UK","Occupation":"Actor","Follower":1099},
    {"Name":"Leonardo DiCaprio","Country":"US","Occupation":"Actor,Producer","Follower":1399},
    {"Name":"Daniel Jacob Radcliffe","Country":"London","Occupation":"Actor","Follower":1091},
]